# Generated by Django 5.2.7 on 2026-03-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessogeral_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autoriza_notificacoes',
            field=models.BooleanField(default=True),
        ),
    ]
