# Generated by Django 5.2.7 on 2026-04-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocompra',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
    ]
