# Generated by Django 5.2.7 on 2026-04-19 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_alter_historicocompra_titulo_alter_ingresso_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='preco_par',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do par de ingressos'),
        ),
    ]
