# Generated by Django 5.2.7 on 2026-07-12 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0003_ingresso_preco_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocompra',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
