# Generated by Django 5.2.7 on 2026-08-08 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0004_alter_historicocompra_titulo_alter_ingresso_preco_and_more'),
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='time_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingressos_como_casa', to='times.time'),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='time_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingressos_como_visitante', to='times.time'),
        ),
    ]
