# Generated by Django 5.2.7 on 2026-02-22 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_alter_cliente_cpf_alter_cliente_rg"),
        ("ingressos", "0006_alter_historicocompra_data_horario_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicocompra",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clientes",
                to="clientes.cliente",
            ),
        ),
    ]
