# Generated by Django 5.2.7 on 2026-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0010_historicocompra_id_cobranca_asaas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocompra',
            name='id_cobranca_asaas',
        ),
        migrations.AddField(
            model_name='historicocompra',
            name='id_checkout_asaas',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Id do Checkout gerado no Asaas'),
        ),
    ]
