# Generated by Django 5.2.7 on 2026-03-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
    ]
