# Generated by Django 5.2.7 on 2026-03-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='criado_em',
        ),
    ]
